---
title: "Inference for Means"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Inference for Means}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#| include: false
library(umncvmstats)
```

## One Sample t-test
```{r}
one_t_inference(wt ~ 1, data = mtcars2)
```

### Separately by another categorical variable
```{r}
one_t_inference(wt ~ am, data = mtcars2)
```

## Two Sample t-test
```{r}
two_t_inference(wt ~ am, data = mtcars2)
```

### together in one table
```{r}
combine_tests(
  one_t_inference(wt ~ am, data = mtcars2),
  two_t_inference(wt ~ am, data = mtcars2))
```

## Pairwise t-tests
```{r}
combine_tests(
  one_t_inference(wt ~ cyl, data = mtcars2),
  pairwise_t_inference(wt ~ cyl, data = mtcars2))
```

## Paired t-test
```{r}
combine_tests(
  one_t_inference(score1 + score2 ~ 1, data = passfail),
  paired_t_inference(score2 - score1 ~ 1, data = passfail))
```

## Log transformations
By default, responses using `log(...)` are back-transformed. 
To keep the result on the log scale, use `backtransform = FALSE`.

```{r}
combine_tests(
  one_t_inference(log(wt) ~ am, data = mtcars2, backtransform = FALSE),
  two_t_inference(log(wt) ~ am, data = mtcars2, backtransform = FALSE),
  one_t_inference(log(wt) ~ am, data = mtcars2),
  two_t_inference(log(wt) ~ am, data = mtcars2))

combine_tests(
  one_t_inference(log(score1) + log(score2) ~ 1, data = passfail),
  paired_t_inference(log(score2) - log(score1) ~ 1, data = passfail))
```
